trigger:
  branches:
    include:
      - main
variables:
  azureServiceConnection: 'my-connection'
  resourceGroupName: 'rg-devops'
  acrName: 'vaishnaviregistry13601'
  acrLoginServer: 'vaishnaviregistry13601.azurecr.io'
  aksClusterName: 'devops-cluster'
  keyVaultName: 'mysecret1717'
  imageName: 'mycustompy'
  imageTag: 'v1'
stages:
  - stage: Build
    displayName: 'Build Docker Image'
    jobs:
      - job: BuildJob
        displayName: 'Building Docker Image'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
          - task: Docker@2
            displayName: Build Docker Image
            inputs:
              command: build
              repository: $(imageName)
              Dockerfile: 'Dockerfile'
              tags:
                $(imageTag)
  - stage: Push
    displayName: Push Image to ACR
    dependsOn: Build
    jobs:
    - job: PushImage
      displayName: Push Docker Image
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - checkout: self
      - task: AzureCLI@2
        displayName: Login to Azure
        inputs:
          azureSubscription: $(azureServiceConnection)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            echo "Logging in to Azure..."
            az account show
            echo "Logging in to ACR..."
            az acr login --name $(acrName)
      - task: Docker@2
        displayName: Push Docker Image to ACR
        inputs:
          command: push
          repository: $(imageName)
          Dockerfile: Dockerfile
          containerRegistry: my-acr-sc
          tags: |
            $(imageTag)
  - stage: Getsecrets
    displayName: 'Get Secrets from Key Vault'
    dependsOn: Build
    jobs:
      - job: GetSecrets
        displayName: 'Retrieve Secrets'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureKeyVault@2
            inputs:
              azureSubscription: $(azureServiceConnection)
              KeyVaultName: $(keyVaultName)
              SecretsFilter: '*'
              RunAsPreJob: false
          - bash: |
              echo "Retrieved secrets from Key Vault:"
              echo "Secret vaule is not displayed"
            displayName: 'Validate keyVault access'
  - stage: Deploy
    displayName: 'Deploy to AKS'
    dependsOn:
      - Build 
      - Getsecrets
    jobs:
      - job: AKSDeployJob
        displayName: 'Deploying to AKS'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
          - task: AzureCLI@2
            displayName: 'Get AKS credential'
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az aks get-credentials --resource-group $(resourceGroupName) --name $(aksClusterName) --overwrite-existing
          - bash: |
              kubectl create secret generic app-secrets --from-literal=secret1=mysecret@123 --dry-run=client -o yaml | kubectl apply -f -
            displayName: Create k8s secret
          - bash: |    
              kubectl apply -f k8s/Deployment.yaml
              kubectl apply -f k8s/service.yaml
            displayName: 'Deploy to AKS'
